### ISSUE TITLE
裏で動かしているAndroidサービスが、Lingrからのレスポンスによって無限にエラーを吐き続ける

### ISSUE THREAD

**Issue by kamichidu** [akechi/project-l#9]
多分、端末の復帰時や、接続断からの再接続時など。
エラーが発生したら、復帰可能 (Lingrからのエラー) であれば一定時間の待ち時間の後に再度初期化を行う。

**Comment by kamichidu** [comment]
```
    jp.michikusa.chitose.lingr.LingrException: not_found - not found: room
            at jp.michikusa.chitose.lingr.LingrClient.sendRequest(LingrClient.java:307)
            at jp.michikusa.chitose.lingr.LingrClient.observe(LingrClient.java:265)
            at akechi.projectl.CometService$ObserveLoader.loadInBackground(CometService.java:292)
            at akechi.projectl.CometService$ObserveLoader.loadInBackground(CometService.java:279)
            at akechi.projectl.async.LingrTaskLoader.loadInBackground(LingrTaskLoader.java:71)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at akechi.projectl.CometService$5.onLoadInBackground(CometService.java:214)
            at akechi.projectl.CometService$5.onLoadInBackground(CometService.java:208)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```
